# =============================================
# SITE CONFIG
# =============================================

name: Tawja
homepage: http://www.tawja.org
lang: fr
slogan: Méthodologie & Boîte à outils pour construire des applications modernes modulaires
year: 2015
copyright: Some rights reserved
